
source 'https://github.com/wintersweet/MySpecs.git'
use_frameworks!

platform :ios, '9.0'

target 'FuseGroupsKits_Example' do
  pod 'FuseGroupsKits', :path => '../'

  target 'FuseGroupsKits_Tests' do
    inherit! :search_paths

    
  end
end
